[project]
name = "typetrace"
version = "0.1.0"
description = "型変換関数のトレーシングシステム"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "pytest>=8.4.2",
    "pydantic>=2.0.0",
    "lightgbm>=4.0.0",
    "scikit-learn>=1.3.0",
    "pyarrow>=14.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pyright>=1.1.406",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.13.3",
    "radon>=6.0.1",
    "xenon>=0.9.3",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]
addopts = [
    "-v",
    "--strict-markers",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html:output/reports/coverage",
    "--cov-report=json:output/reports/coverage.json",
]
markers = [
    "e2e: End-to-end tests",
    "unit: Unit tests",
    "integration: Integration tests",
    "slow: Slow running tests",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "W", "ANN", "B", "S", "C90", "PLR"]
ignore = ["S101", "B008", "ANN204", "B017", "ANN201"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN", "S", "B"]
"src/html_reporter.py" = ["E501", "C901", "PLR0912", "PLR0915", "PLR2004", "S112"]
"run_trace.py" = ["ANN401"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pylint]
max-args = 7
max-branches = 12
max-statements = 50

[tool.pyright]
typeCheckingMode = "basic"
include = ["src", "components"]
exclude = ["tests", ".venv"]

[tool.radon]
exclude = ["tests/*", "docs/*"]
cc_min = "A"
mi_min = 70

[tool.xenon]
max-absolute = "B"
max-modules = "B"
max-average = "A"
exclude = ["tests/*", "docs/*"]
