[project]
name = "xform-core"
version = "0.1.0"
description = "Core primitives for defining and normalizing TransformFn objects."
authors = [{ name = "TransformFn Authors" }]
requires-python = ">=3.11"
dependencies = [
    "typing-extensions>=4.11.0",
]

[project.optional-dependencies]
dev = [
    "mypy>=1.10.0",
    "pytest>=8.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["xform_core"]

[tool.uv]
package = true
