[project]
name = "proj-dtypes"
version = "0.1.0"
description = "Project-specific data types, example generators, and validation checks."
authors = [{ name = "TransformFn Authors" }]
requires-python = ">=3.11"
dependencies = [
    "xform-core",
    "numpy>=1.26.0",
    "pandas>=2.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["proj_dtypes"]

[tool.uv]
package = true
