[project]
name = "xform-auditor"
version = "0.1.0"
description = "CLI utilities for auditing TransformFn annotations by executing Examples and Checks."
authors = [{ name = "TransformFn Authors" }]
requires-python = ">=3.11"
dependencies = [
    "xform-core",
    "click>=8.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
]

[project.scripts]
xform-auditor = "xform_auditor.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["xform_auditor"]

[tool.uv]
package = true
